### ISSUE TITLE
可否直接用HttpURLConnection写下载等逻辑，从而不必引入okhttp？

### ISSUE THREAD

**Issue by VictorChow** [fccaikai/AppUpdate#2]
可否直接用HttpURLConnection写下载等逻辑，从而不必引入okhttp？

**Comment by caikaidev** [comment]
谢谢建议，下一步会移除okhttp。自己用HttpURLConnection实现，减少依赖其他的库。

**Comment by caikaidev** [comment]
已更新为HttpURLConnection实现
