### ISSUE TITLE
Override String Values

### ISSUE THREAD

**Issue by iamnotacoder-djs** [fccaikai/AppUpdate#5]
Thank you for this library.

Is it possible to replace 
`String.format("正在下载（%s/%s）"...` with
`String.format(...string.someid+"（%s/%s）"`? (fragment of your code from decompilier)

Could you also transit all string values to library's string resourse file? And reveal list of ids of this strings for developers, which creates applications with another languages?

Sorry for my bad English :]

**Comment by caikaidev** [comment]
Hi,you can updated to version 2.1.1 .
All string resourse in `strings.xml`
see  [strings.xml](https://github.com/fccaikai/AppUpdate/blob/master/lib/src/main/res/values/strings.xml)

**Comment by iamnotacoder-djs** [comment]
Ok. Thank you. 
Please fix setup on [https://android-arsenal.com/details/1/5431](url) (if u can)
