### ISSUE TITLE
下载失败进度条不消失

### ISSUE THREAD

**Issue by wpj19910910** [fccaikai/AppUpdate#6]
立刻检查 自定义界面 下载失败后进度条不消失
![image](https://cloud.githubusercontent.com/assets/15603616/25424265/622cebdc-2a9a-11e7-8e42-2d0ec9056bac.png)

**Comment by caikaidev** [comment]
你好，这边的逻辑现在是这样的。
现在配置文件设置成了强制更新。所以就算下载失败的话，也没有将弹出框移除。如果App是需要强制更新的话，那么肯定是这个版本有缺陷或者是不能使用的，如果弹出框消失了，App就能够继续使用了。

**Comment by wpj19910910** [comment]
好的~~了解了

**Comment by caikaidev** [comment]
做了一些修改，下载失败的时候，会隐藏下载进度条，显示出升级提示的Dialog。请升级到最新版本2.1.2
