### ISSUE TITLE
4.4机器上不能正确检测版本，提示已是最新版

### ISSUE THREAD

**Issue by nicefan** [fccaikai/AppUpdate#7]
在高版本上正常。

**Comment by caikaidev** [comment]
具体机型能提供一下吗，我这边没有4.4的机器，但是我在4.4的模拟器上是ok的

**Comment by nicefan** [comment]
反复测试，发现是使用了https协议地址的问题，将json地址和apk地址改成http就正常了

**Comment by caikaidev** [comment]
目前不支持https协议。后续会加进去。

**Comment by nicefan** [comment]
但是6.0的没问题，希望尽快解决一下了！

**Comment by caikaidev** [comment]
ok，谢谢反馈，我尽快解决。

**Comment by caikaidev** [comment]
已添加https支持。请升级到2.1.3版本。

**Comment by nicefan** [comment]
速度好快，赞一个，明天上班了试试

发自我的超级手机
